on:
    push:
  
jobs:
    build-and-push-image:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
  
      container:
         image: quay.io/singularity/singularity:v4.1.0
         options: --privileged
  
      name: Build Apptainer Container
      steps:
        - name: Check out code for the container builds
          uses: actions/checkout@v4
  
        - name: Build Container
          run: |
             sudo -E singularity build hello.sif docker://hello-world
  
        - name: Login and Deploy Container
          run: |
             echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
             singularity push hello.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest




